import './style.css';

type Product = { id: number; name: string; description: string; price_cents: number | null; currency: string; stock_note: string; visible: boolean };
type Catalog = { business_name: string; client_name: string; expires_at: string; products: Product[] };
type Item = { product_id: number; quantity: number };
const $ = <T extends Element>(s: string) => document.querySelector(s) as T;
const app = $('#app');
const path = location.pathname;
const clientToken = new URLSearchParams(location.search).get('client') || 'demo-client';
let basket: Item[] = [];
let catalog: Catalog | null = null;
let ownerCode = sessionStorage.getItem('crc-owner-code') || '';

function esc(value: string) { const d = document.createElement('div'); d.textContent = value; return d.innerHTML; }
function money(cents: number | null, currency = 'USD') { return cents === null ? 'Price on application' : new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(cents / 100); }
function api(url: string, init?: RequestInit) { return fetch(url, { ...init, headers: { 'content-type': 'application/json', ...(ownerCode ? { 'x-owner-code': ownerCode } : {}), ...(init?.headers || {}) } }); }
function isOwner() { return path === '/owner'; }

function shell(content: string, title = 'Client Request Catalog') {
  app.innerHTML = `<header class="site-head"><a class="wordmark" href="/?client=${encodeURIComponent(clientToken)}">REQUEST<br><i>SLIP</i></a><nav aria-label="Primary"><a href="/?client=${encodeURIComponent(clientToken)}">Catalog</a><a href="/owner">Owner workspace</a><a href="/terms">Terms</a></nav></header><main id="main">${content}</main><footer><span>Made as an original two-ink illustration · no trackers</span><span><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a></span></footer>`;
}

function itemCount() { return basket.reduce((n, item) => n + item.quantity, 0); }
function renderCatalog() {
  if (!catalog) return;
  const offers = catalog.products.length ? catalog.products.map(p => `<article class="offer" data-id="${p.id}"><div><p class="eyebrow">${p.price_cents === null ? 'Made to quote' : 'Fixed price'}</p><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><small>${esc(p.stock_note || 'Availability confirmed when we quote')}</small></div><div class="offer-action"><strong>${money(p.price_cents, p.currency)}</strong><button class="add" data-id="${p.id}">${p.price_cents === null ? 'Request a quote' : 'Add to request'}</button></div></article>`).join('') : `<section class="empty"><h2>No offers are visible yet</h2><p>This private catalog is being prepared. Ask the business when its next request window opens.</p></section>`;
  shell(`<section class="mast"><div><p class="eyebrow">Private client catalog · expires ${new Date(catalog.expires_at).toLocaleDateString()}</p><h1>${esc(catalog.business_name)}<br><em>for ${esc(catalog.client_name)}</em></h1><p class="lede">Select what you need. Fixed prices are noted; everything else becomes a clear quote request. Nothing is charged here.</p><a class="stamp" href="#request">Start a request <span aria-hidden="true">↓</span></a></div><img src="/assets/request-desk.webp" width="960" height="640" fetchpriority="high" decoding="async" alt="A blank request slip with a ruler and spool, printed in green and red ink." /></section><section class="catalog-head"><div><p class="eyebrow">Available to you</p><h2>Choose your next job</h2></div><p>Prices and availability are private to this link.</p></section><section class="offers" aria-label="Available products">${offers}</section><section id="request" class="request-slip" aria-labelledby="request-title"><div class="slip-heading"><p class="eyebrow">Your request · <span id="count">${itemCount()}</span> item${itemCount() === 1 ? '' : 's'}</p><h2 id="request-title">Make it quote-ready</h2><p id="basket-copy">${basket.length ? 'We’ll include your selected items below.' : 'Choose an offer above, then tell us where to send the quote.'}</p></div><form id="request-form" novalidate><div class="form-grid"><label>Your name<input name="name" autocomplete="name" required /></label><label>Email for the quote<input name="email" type="email" autocomplete="email" required /></label><label>Phone <span>(optional)</span><input name="phone" type="tel" autocomplete="tel" /></label><label>Reference or PO number <span>(optional)</span><input name="reference" /></label></div><label>Anything we should know?<textarea name="note" rows="3" placeholder="Timing, size, colour, delivery…"></textarea></label><p id="form-message" class="form-message" aria-live="polite"></p><button class="submit" type="submit">Send request <span aria-hidden="true">→</span></button></form></section><section class="plus"><div><p class="eyebrow">Catalog Plus</p><h2>Keep every client link in its lane.</h2><p>$29 one-time unlock for additional client links and branded request receipts. Sociobot/Dodo is merchant of record.</p></div><div><a class="button-outline" href="https://api.sociobot.in/api/v1/products/client-request-catalog/checkout">Unlock Plus</a><button class="text-button" id="restore">Have a license?</button></div></section>`, catalog.business_name);
  document.querySelectorAll<HTMLButtonElement>('.add').forEach(button => button.addEventListener('click', () => addItem(Number(button.dataset.id))));
  $('#request-form').addEventListener('submit', submitRequest);
  $('#restore').addEventListener('click', restoreLicense);
}
function addItem(id: number) {
  const found = basket.find(i => i.product_id === id);
  if (found) found.quantity += 1; else basket.push({ product_id: id, quantity: 1 });
  const count = $('#count'); if (count) count.textContent = String(itemCount());
  const copy = $('#basket-copy'); if (copy) copy.textContent = `${itemCount()} item${itemCount() === 1 ? '' : 's'} selected. You can add more or send when ready.`;
  const button = document.querySelector<HTMLButtonElement>(`.add[data-id="${id}"]`); if (button) { button.textContent = 'Added ✓'; setTimeout(() => button.textContent = catalog?.products.find(x => x.id === id)?.price_cents === null ? 'Request a quote' : 'Add to request', 900); }
}
async function submitRequest(event: SubmitEvent) {
  event.preventDefault(); const form = event.currentTarget as HTMLFormElement; const message = $('#form-message'); const body = Object.fromEntries(new FormData(form));
  if (!String(body.name).trim() || !String(body.email).includes('@') || !basket.length) { message.textContent = !basket.length ? 'Choose at least one offer before sending.' : 'Enter your name and a valid email address.'; return; }
  const button = $('button[type="submit"]') as HTMLButtonElement; button.disabled = true; button.textContent = 'Sending…';
  try { const res = await api(`/api/catalog/${encodeURIComponent(clientToken)}/requests`, { method: 'POST', body: JSON.stringify({ ...body, items: basket }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'We could not send that request.'); basket = []; form.reset(); message.textContent = `Request ${data.reference} is in the inbox. We’ll reply to ${body.email}.`; } catch (error) { message.textContent = navigator.onLine ? (error as Error).message : 'You appear to be offline. Reconnect, then send your request.'; } finally { button.disabled = false; button.innerHTML = 'Send request <span aria-hidden="true">→</span>'; const count = $('#count'); if (count) count.textContent = '0'; }
}
async function loadCatalog() { shell(`<section class="loading"><p class="eyebrow">Checking private link</p><h1>Opening your catalog…</h1></section>`); try { const res = await api(`/api/catalog/${encodeURIComponent(clientToken)}`); if (!res.ok) throw new Error(res.status === 410 ? 'This client link has expired.' : 'This catalog could not be opened.'); catalog = await res.json(); renderCatalog(); } catch (error) { shell(`<section class="empty"><p class="eyebrow">Private link unavailable</p><h1>${esc((error as Error).message)}</h1><p>Check the complete link from the business, or ask them to send a new one.</p><button onclick="location.reload()">Try again</button></section>`); } }
async function verifyLicense(token: string) { const key = 'sb_license:client-request-catalog:verdict'; try { const cached = JSON.parse(localStorage.getItem(key) || '{}'); if (cached.token === token && Date.now() - cached.checked < 86400000) return cached.valid; const r = await fetch(`https://api.sociobot.in/api/v1/products/client-request-catalog/verify?license=${encodeURIComponent(token)}`); const data = await r.json(); localStorage.setItem(key, JSON.stringify({ token, valid: data.valid, checked: Date.now() })); return data.valid; } catch { return true; } }
async function restoreLicense() { const token = prompt('Paste your license token'); if (!token) return; localStorage.setItem('sb_license:client-request-catalog', token.trim()); const valid = await verifyLicense(token.trim()); alert(valid ? 'License restored.' : 'That license is no longer active.'); }
function loadLicenseFromUrl() { const query = new URLSearchParams(location.search); const license = query.get('license'); if (license) { localStorage.setItem('sb_license:client-request-catalog', license); query.delete('license'); history.replaceState({}, '', `${path}${query.toString() ? '?' + query : ''}`); void verifyLicense(license); } else { const existing = localStorage.getItem('sb_license:client-request-catalog'); if (existing) void verifyLicense(existing); } }

function loginScreen(message = '') { shell(`<section class="owner-login"><p class="eyebrow">Owner workspace</p><h1>The request inbox, without the shop.</h1><p>Enter the owner code created when this catalog started. It is shown in the service logs and is not part of any client link.</p><label>Owner code<input id="owner-code" autocomplete="off" /></label><p id="owner-message" class="form-message">${esc(message)}</p><button id="owner-login">Open inbox</button></section>`); $('#owner-login').addEventListener('click', async () => { ownerCode = ($('#owner-code') as HTMLInputElement).value; sessionStorage.setItem('crc-owner-code', ownerCode); await loadOwner(); }); }
async function loadOwner() { if (!ownerCode) return loginScreen(); shell(`<section class="loading"><h1>Opening your inbox…</h1></section>`); try { const res = await api('/api/admin/overview'); if (res.status === 401) { ownerCode = ''; sessionStorage.removeItem('crc-owner-code'); return loginScreen('That code did not match. Try the code in the service startup log.'); } const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Could not load inbox'); renderOwner(data); } catch (error) { loginScreen((error as Error).message); } }
function renderOwner(data: any) { const requests = data.requests.length ? data.requests.map((r: any) => `<li class="inbox-row"><div><strong>${esc(r.reference)}</strong><span class="status ${esc(r.status)}">${esc(r.status)}</span><p>${esc(r.name)} · ${esc(r.email)}${r.note ? `<br>${esc(r.note)}` : ''}</p><small>${esc(r.items)}</small></div><div><time>${new Date(r.created_at).toLocaleDateString()}</time><select data-status="${r.id}" aria-label="Status for ${esc(r.reference)}"><option ${r.status === 'new' ? 'selected' : ''}>new</option><option ${r.status === 'quoted' ? 'selected' : ''}>quoted</option><option ${r.status === 'closed' ? 'selected' : ''}>closed</option></select></div></li>`).join('') : `<li class="empty"><h2>Your inbox is clear</h2><p>Share your client link to start receiving quote-ready requests.</p></li>`;
  shell(`<section class="owner-head"><div><p class="eyebrow">Owner workspace</p><h1>${esc(data.business_name)}<br><em>request desk</em></h1><p>Client link: <code>${location.origin}/?client=${esc(data.demo_client_token)}</code></p></div><div class="owner-actions"><a class="button-outline" href="/api/admin/requests.csv" id="csv">Export CSV</a><a class="button-outline" href="/api/admin/requests.pdf" id="pdf">Export PDF</a><button id="logout">Lock workspace</button></div></section><section class="metrics"><div><strong>${data.requests.filter((r: any) => r.status === 'new').length}</strong><span>New requests</span></div><div><strong>${data.products.length}</strong><span>Visible offers</span></div><div><strong>${data.clients}</strong><span>Client links</span></div></section><section class="owner-grid"><section><div class="section-title"><h2>Request inbox</h2><span>Data stays in your catalog</span></div><ul class="inbox">${requests}</ul></section><section class="product-editor"><div class="section-title"><h2>Add an offer</h2><span>Quote-first by default</span></div><form id="product-form"><label>Name<input name="name" required /></label><label>Description<textarea name="description" required rows="2"></textarea></label><div class="form-grid"><label>Price in cents <span>(blank = POA)</span><input name="price_cents" type="number" min="0" /></label><label>Stock note<input name="stock_note" placeholder="Confirmed on request" /></label></div><p class="form-message" id="product-message" aria-live="polite"></p><button>Add offer</button></form><hr><h2>Privacy controls</h2><p>Export or delete all stored request data for this catalog.</p><button class="danger" id="delete-data">Delete request data</button></section></section>`);
  for (const [id, endpoint, name] of [['csv', '/api/admin/requests.csv', 'client-requests.csv'], ['pdf', '/api/admin/requests.pdf', 'client-requests.pdf']] as const) { ($("#" + id) as HTMLAnchorElement).onclick = async e => { e.preventDefault(); const res = await api(endpoint); if (!res.ok) return alert('Export could not be created.'); const url = URL.createObjectURL(await res.blob()); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }; }
  $('#logout').addEventListener('click', () => { sessionStorage.removeItem('crc-owner-code'); ownerCode = ''; loginScreen(); });
  document.querySelectorAll<HTMLSelectElement>('[data-status]').forEach(select => select.addEventListener('change', async () => { await api(`/api/admin/requests/${select.dataset.status}`, { method: 'PATCH', body: JSON.stringify({ status: select.value }) }); }));
  $('#product-form').addEventListener('submit', async event => { event.preventDefault(); const obj = Object.fromEntries(new FormData(event.currentTarget as HTMLFormElement)); const r = await api('/api/admin/products', { method: 'POST', body: JSON.stringify(obj) }); $('#product-message').textContent = r.ok ? 'Offer added to this client catalog.' : 'Could not add that offer.'; if (r.ok) { (event.currentTarget as HTMLFormElement).reset(); setTimeout(loadOwner, 500); } });
  $('#delete-data').addEventListener('click', async () => { if (!confirm('Delete every request and contact detail? This cannot be undone.')) return; const r = await api('/api/admin/requests', { method: 'DELETE' }); if (r.ok) loadOwner(); });
}
function legal(kind: 'privacy' | 'terms') { const privacy = kind === 'privacy'; shell(`<article class="legal"><p class="eyebrow">${privacy ? 'Privacy' : 'Terms'}</p><h1>${privacy ? 'Your request stays a request.' : 'A quote-first catalog, not a checkout.'}</h1><h2>${privacy ? 'What we store' : 'Using this service'}</h2><p>${privacy ? 'When you submit a request, the business receives your name, email, optional phone and reference, selected offers, and note. This information is stored in its catalog inbox so it can prepare a quote. We do not use advertising or tracking scripts.' : 'This product lets a business collect requests. Submitting a request does not create a purchase, reserve stock, or guarantee a price. The business will confirm availability and quote terms directly.'}</p><h2>${privacy ? 'Your choices' : 'Plus unlock'}</h2><p>${privacy ? 'Ask the business that sent you the link to export or delete your request. Owners can delete stored request data from their workspace. Private links are access credentials; do not forward them.' : 'Catalog Plus is a one-time $29 license unlock administered by Sociobot/Dodo, merchant of record. A refunded or revoked license loses its unlocked features. Core catalog use and request export remain available without it.'}</p><p><a href="/?client=${encodeURIComponent(clientToken)}">Return to catalog</a></p></article>`); }
loadLicenseFromUrl();
if (path === '/owner') void loadOwner(); else if (path === '/privacy' || path === '/terms') legal(path.slice(1) as 'privacy' | 'terms'); else void loadCatalog();
